[package]
name = "epsg"
version = "0.1.0"
authors = ["Alex Collins"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = {version = "0.17.4", features = ["with-time-0_2"] }
handlebars = "3.2.1"
# chrono = "0.4.13"
serde_json = "1.0.56"
serde = { version = "1.0.114", features = ["derive"] }
time = "0.2.16"
