[package]
name = "epsg"
version = "0.4.0"
authors = ["Alex Collins"]
edition = "2018"
homepage = "https://github.com/atcol/epsg"
keywords = ["epsg", "ogc", "geo", "crs", "coordinates"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/atcol/epsg"
description = "EPSG Coordinate Reference System tools & data"

[dependencies]
phf = { version = "0.8.0", features = ["macros"] }
postgres = { version = "0.18.1", features = ["with-time-0_2"] }
handlebars = "3.5.1"
serde_json = "1.0.59"
serde = { version = "1.0.117", features = ["derive"] }
time = "0.2.22"
