version: '2.0'

services:

  db:
    image: postgres:9.6
    restart: always
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: "epsg"
    ports:
      - 5432:5432
