version: '2.0'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./EPSG-v9_8_13-v10model-PostgreSQL:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: "epsg"
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
